config/routes.rb
Rails.application.routes.draw do

  root to: 'categories#index'
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/articles' => 'articles#index' 
  # get '/articles/new' => 'articles#new', as: 'new_article'
  # post '/articles' => 'articles#create', as: 'create_article'
  # get '/articles/:id' => 'articles#show', as: 'show_article'
  # get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  # post '/articles/:id' => 'articles#update', as: 'update_article'
  # delete '/articles/:id' => 'articles#delete', as: 'delete_article'
  get '/today' => 'tasks#today'
  
  resources :articles do
    resources :comments
  end
  
  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true
    validates :name, length: { minimum: 3 }
    # validates :name, uniqueness: true
    
    validates :body, presence: true
    validates :body, length: { minimum: 5 }

    has_many :comments
end

app/models/author.rb
class Author < ApplicationRecord
    validates :name, uniqueness: true
    validates :genre, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :name, length: { maximum: 20 }

    has_many :tasks
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article 
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, presence: true
    validates :name, length: { maximum: 20 }

    validates :details, presence: true
    validates :details, length: { maximum: 40 }

    validates :scheduled_at, presence: true
    validates :category, presence: true

    belongs_to :category 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def show
        @article = Article.find(params[:id])
        @comments = @article.comments
    end
    
    def create
        @article = Article.new(article_params)

        if @article.save 
            redirect_to articles_path
        else 
            render :new
        end
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def show
        @category = Category.find(params[:id])
        @tasks = @category.tasks
    end
    
    def create
        @category = Category.new(category_params)

        respond_to do |format|
            if @category.save
              format.html { redirect_to categories_path, notice: "Task was successfully created." }
              format.json { render :show, status: :ok, location: categories_path}
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @category.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        
        if @category.update(category_params)
            redirect_to categories_path
        end
    end
    
    def destroy
        @category = Category.find(params[:id])
        @category.destroy

        redirect_to categories_path
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :get_article

    def index
        @comments = @article.comments
    end

    def new
        @comment = @article.comments.build
        # @comment = Comment.new
    end

    def create
        @comment = @article.comments.build(comment_params)

        if @comment.save
            redirect_to article_comment_path(@article.id, @comment.id)
        else
            render :new
        end
    end

    def show
        @comment = Comment.find(params[:id])
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def update
        @comment = Comment.find(params[:id])

        if @comment.update(comment_params)
            redirect_to article_comment_path(@article.id, @comment.id)
        end
    end

    def destroy
        @comment = Comment.find(params[:id]).destroy

        redirect_to article_path(@article.id)
    end

    private

    def get_article
        @article = Article.find(params[:article_id])
    end

    def comment_params
        params.require(:comment).permit(:body, :article_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :get_category, except: [:today]

  # GET /tasks or /tasks.json
  def index
    @tasks = @category.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = @category.tasks.build
  end

  # GET /tasks/1/edit
  def edit
    @tasks = Task.find(params[:id])
  end

  def create
    @task = @category.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to category_path(@category.id), notice: "Task was successfully created." }
        format.json { render :show, status: :ok, location: category_task_path(@category.id, @task.id)}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to category_path(@category.id), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task = Task.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to category_path(@category.id), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def today
    @tasks = Task.where("DATE(scheduled_at) = ?", Date.today)
  end

  private

    def get_category
      @category = Category.find(params[:category_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :details, :scheduled_at, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<%# <%= form_with url: update_article_path, local: true do |f| %> %>
<%= form_for @article do |f| %>
<p>
    <% if @article.errors.any? %>
        <ul>
        <% @article.errors.full_messages.each do |message| %>
            <li><%= message %>
        <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :body %><br/>
    <%= f.text_field :body %>
</p>

<p>
<%= f.submit "update" %>
</p>

<% end %>

app/views/articles/index.html.erb
<table>
    <thead>
        <tr>
            <th>count</th>
            <th>ID</th>
            <th>Name</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% counter = 1 %>
        <% @articles.each do |article| %>
            <tr>
                <td><%= counter %></td>
                <td><%= article.id %></td>
                <td><%= article.name %></td>
                <td><%= article.body %></td>
                <td><%= link_to 'edit article', edit_article_path(article) %></td>
                <td><%= link_to 'show article', article %></td>
                <td><%= link_to 'delete article', article, method: :destroy, data: { confirm: "Are you sure?"} %></td>
                
                <%# <td><%= link_to 'edit article', edit_article_path(article) %></td> %>
                <%# <td><%= link_to 'show article', show_article_path(article) %></td> %>
                <%# <td><%= link_to 'delete article', delete_article_path(article), method: :delete, data: { confirm: "Are you sure?"} %></td> %>
            </tr>
            <% counter += 1%>
        <% end %>
    </tbody>
</table>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>

<p>
    <% if @article.errors.any? %>
        <ul>
        <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :body %><br/>
    <%= f.text_field :body %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

app/views/articles/show.html.erb

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Body</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @article.id %></td>
            <td><%= @article.name %></td>
            <td><%= @article.body %></td>
        </tr>
    </tbody>
</table>

MANUAL: 
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Body</th>
        </tr>
    </thead>
    <tbody>
        <% @comments.each do |comment| %>
            <tr>
                <td><%= comment.id %></td>
                <td><%= comment.body %></td>
                <td><%= link_to 'Edit', edit_article_comment_path(@article.id, comment.id) %></td>
                <td><%= link_to 'Delete', article_comment_path(@article.id, comment.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>

            </tr>
        <% end %>
    </tbody>
</table>

PARTIAL: 
<%= render 'comments/index' %>
<%# <%=link_to 'edit comment', edit_article_comment_path(@article.id, @comment)%> %>

<%# removed 'comments: @comments' %>

app/views/categories/edit.html.erb
<%= form_for @category do |f| %>

<p>
    <% if @category.errors.any? %>
        <ul>
        <% @category.errors.full_messages.each do |message| %>
            <li><%= message %>
        <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
<%= f.submit "update" %>
</p>

<% end %>

app/views/categories/index.html.erb
<table>
    <thead>
        <tr>
            <th><h1>Category</h1></th>
        </tr>
    </thead>

    <tbody>
        <% @categories.each do |category| %>
            <tr>
                <td><%= category.name %></td>
                <td><%= link_to 'edit category', edit_category_path(category) %></td>
                <td><%= link_to 'show category', category %></td>
                <td><%= link_to 'delete category', category, method: :delete, data: { confirm: "Are you sure?"} %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'New Category', new_category_path %>

<%= form_with url: "/users/sign_out", method: :delete do |form| %>
  <%= form.submit "Sign out" %>
<% end %>

app/views/categories/new.html.erb
<%= form_for @category do |f| %>

<p>
    <% if @category.errors.any? %>
        <ul>
        <% @category.errors.full_messages.each do |message| %>
            <li><%= message %>
        <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.text_field :name %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

app/views/categories/show.html.erb

<table>
    <thead>
        <h1>Category<h1>
    </thead>
    <tbody>
        <tr>
            <td><%= @category.name %></td>
        </tr>
    </tbody>
</table>

<%= render 'tasks/index' %>

<%= link_to 'Back to Category list', categories_path %>

app/views/comments/_index.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% @comments.each do |comment| %>
            <tr>
                <td><%= comment.id %></td>
                <td><%= comment.body %></td>      
                <td><%= link_to 'edit comment', edit_article_comment_path(@article.id, comment) %></td>
                <td><%= link_to 'delete comment', article_comment_path(@article.id, comment), method: :delete, data: { confirm: "Are you sure?"} %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'add comment', new_article_comment_path(@article) %>

app/views/comments/edit.html.erb
<%= form_with model: [@article, @comment], local: true do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body %>

    <%= f.submit 'update' %>

<% end %>

app/views/comments/index.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% @comments.each do |comment| %>
            <tr>
                <td><%= comment.id %></td>
                <td><%= comment.body %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add Comment', new_article_comment_path(@article) %>

app/views/comments/new.html.erb
<%= form_with model: [@article, @comment], local: true do |f| %>
    <p>
        <% if @comment.errors.any? %>
            <ul>
                <% @comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
    </p>

    <p>
        <%= f.label :body %>
        <%= f.text_field :body %>
    </p>
    <p>
        <%= f.submit 'comment' %>
    </p>
<% end %>

app/views/comments/show.html.erb
<table>
    <tbody>
        <tr>
            <td><%= @comment.body %></td>
        </tr>
    </tbody>
</table>

<%= link_to 'back to article', @article %>
<%# <%= link_to 'back to article', @comment.article %> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_index.html.erb
<p id="notice"><%= notice %></p>
  <h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Details</th>
      <th>Category</th>
      <th>Scheduled at</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.name %></td> 
        <td><%= task.details %></td> 
        <td><%= task.category.name %></td> 
        <td><%= task.scheduled_at %></td> 
        
        <td><%= link_to 'Show', category_task_path(@category, task) %></td>
        <td><%= link_to 'Edit', edit_category_task_path(@category, task) %></td>
        <td><%= link_to 'Destroy', category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Task', new_category_task_path(@category) %>

app/views/tasks/_new.html.erb
<%= form_with model: @task do |f| %>

    <h1>New Task</h1>

    <%# <%= render 'tasks/form', task: @task %>

    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :details %><br/>
        <%= f.text_field :details %>
    </p>

    <p>
        <%= f.label :scheduled_at %><br/>
        <%= f.datetime_select :scheduled_at %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Back to catgories', categories_path %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%# <%= render 'form', task: @task %> %>
<%= form_with model: [@category, @task], local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :details %>
    <%= f.text_field :details %>

    <%= f.label :scheduled_at %>
    <%= f.date_field :scheduled_at %>

    <%= f.submit 'update' %>

<% end %>
<%= link_to 'Show', category_task_path %>
<%= link_to 'Back', category_tasks_path %>

app/views/tasks/new.html.erb
<%= form_with model: [@category, @task],  local: true do |f| %>

    <h1>New Task for <%= @category.name %></h1>

    <%# <%= render 'tasks/form', task: @task %>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :details %><br/>
        <%= f.text_field :details %>
    </p>

    <p>
        <%= f.label :scheduled_at %><br/>
        <%= f.date_field :scheduled_at %>
    </p>

    <%= f.submit %>
    </p>
<% end %>



<p>
<br/><%= link_to 'Back to Category list', categories_path %>
</p>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Task for <%= @category.name%></h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Details</th>
            <th>Schedule</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @task.name %></td>
            <td><%= @task.details %></td>
            <td><%= @task.scheduled_at %></td>
        </tr>
    </tbody>
</table>


<%= link_to 'Edit', edit_category_task_path(@task) %> |
<%= link_to 'Back', category_tasks_path %>

app/views/tasks/today.html.erb
<table>
    <thead>
        <tr>
            <th><h1>Category</h1></th>
        </tr>
    </thead>

    <tbody>
        <% @tasks.each do |task_today| %>
            <tr>
                <% puts task_today %>
                <td><%= task_today.name %></td>
            </tr>
        <% end %>
    </tbody>
</table>